# Generated by Django 3.2.7 on 2021-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('idx', models.BigAutoField(db_column='IDX', primary_key=True, serialize=False)),
                ('crtfckey', models.CharField(blank=True, db_column='crtfcKey', max_length=100, null=True)),
                ('logdt', models.CharField(blank=True, db_column='logDt', max_length=25, null=True)),
                ('usese', models.CharField(blank=True, db_column='useSe', max_length=200, null=True)),
                ('sysuser', models.CharField(blank=True, db_column='sysUser', max_length=60, null=True)),
                ('conectip', models.CharField(blank=True, db_column='conectIp', max_length=30, null=True)),
                ('datausgqty', models.IntegerField(blank=True, db_column='dataUsgqty', null=True)),
                ('send_yn', models.CharField(blank=True, db_column='SEND_YN', max_length=1, null=True)),
                ('proc_nm', models.CharField(blank=True, db_column='PROC_NM', max_length=50, null=True)),
            ],
            options={
                'db_table': 'T_SYS_LOG_SF',
                'managed': False,
            },
        ),
    ]
